language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy ahmedmahrousmahmoud/reverseproxy:latest
  - docker tag udagram-api-user ahmedmahrousmahmoud/udagram-api-user:latest
  - docker tag udagram-api-feed ahmedmahrousmahmoud/udagram-api-feed:latest
  - docker tag udagram-frontend ahmedmahrousmahmoud/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ahmedmahrousmahmoud/reverseproxy:v2
  - docker push ahmedmahrousmahmoud/udagram-api-user:v2
  - docker push ahmedmahrousmahmoud/udagram-api-feed:v2
  - docker push ahmedmahrousmahmoud/udagram-frontend:v2

